#!/usr/bin/env bash
#
# Cleanup script for MOTIP
# - Removes the virtual environment (.venv)
# - Cleans up C++ compilation artifacts in models/ops
# - Removes python cache files
#
set -e

# ---------------- Colors ----------------
if tput setaf 0 >/dev/null 2>&1; then
  COLOR_RED="$(tput setaf 1)"
  COLOR_GREEN="$(tput setaf 2)"
  COLOR_RESET="$(tput sgr0)"
else
  COLOR_RED=""
  COLOR_GREEN=""
  COLOR_RESET=""
fi

# ---------------- Safety Check ----------------
FORCE=""
for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE="yes" ;;
    *) ;;
  esac
done

if [[ -z "$FORCE" ]]; then
  echo "${COLOR_RED}WARNING: This will permanently delete the '.venv' directory and build artifacts.${COLOR_RESET}"
  read -p "Are you sure you want to continue? [y/N] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# ---------------- 1. Remove Virtual Environment ----------------
if [ -d ".venv" ]; then
  echo -n "🗑️  Removing .venv... "
  rm -rf .venv
  echo "${COLOR_GREEN}Done${COLOR_RESET}"
else
  echo "ℹ️  .venv not found, skipping."
fi

# ---------------- 2. Clean Compilation Artifacts ----------------
OPS_DIR="models/ops"

if [ -d "$OPS_DIR" ]; then
  echo "🧹 Cleaning compilation artifacts in $OPS_DIR..."
  
  # Remove build directories generated by setup.py
  rm -rf "$OPS_DIR/build"
  rm -rf "$OPS_DIR/dist"
  rm -rf "$OPS_DIR/"*.egg-info
  
  # Remove compiled shared objects (.so) files generated by inplace build
  find "$OPS_DIR" -name "*.so" -type f -delete
  
  echo "${COLOR_GREEN}   Artifacts removed.${COLOR_RESET}"
else
  echo "⚠️  $OPS_DIR not found, skipping compilation cleanup."
fi

# ---------------- 3. Clean PyCache ----------------
echo -n "🧹 Cleaning __pycache__ directories... "
find . -type d -name "__pycache__" -exec rm -rf {} +
echo "${COLOR_GREEN}Done${COLOR_RESET}"

echo ""
echo "${COLOR_GREEN}✅ Cleanup complete.${COLOR_RESET}"
